export const ASTEROIDS_REQUEST = "ASTEROIDS_REQUEST";
export const ASTEROIDS_SUCCEEDED = "ASTEROIDS_SUCCEEDED";
export const ASTEROIDS_FAILED = "ASTEROIDS_FAILED";
export const ADD_SELECTED_ASTEROID = "ADD_SELECTED_ASTEROID";
export const REMOVE_SELECTED_ASTEROID = "REMOVE_SELECTED_ASTEROID";